# Generated by Django 4.0.3 on 2022-09-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brocker_name', models.CharField(max_length=20)),
                ('bill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BrockerPeriodicCommissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('exchange_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShareDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=30)),
                ('type_of_deal', models.CharField(choices=[('BUY_SR', 'BUYING_SHARES'), ('SL_SR', 'SALE_OF_SHARES'), ('DIV', 'DIVIDENT_PAYMENT'), ('BUY_BND', 'BUYING_BOND'), ('SL_BND', 'SALE_OF_BOND'), ('RFL_MN', 'REFILL_MONEY'), ('WD_MN', 'WITHDRAWAL_MONEY'), ('BRK_CM', 'BROKER_COMMISSION'), ('ERR', 'ERROR')], max_length=10)),
                ('datetime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('count', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.bill')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.currency')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.share')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=30)),
                ('type_of_deal', models.CharField(choices=[('BUY_SR', 'BUYING_SHARES'), ('SL_SR', 'SALE_OF_SHARES'), ('DIV', 'DIVIDENT_PAYMENT'), ('BUY_BND', 'BUYING_BOND'), ('SL_BND', 'SALE_OF_BOND'), ('RFL_MN', 'REFILL_MONEY'), ('WD_MN', 'WITHDRAWAL_MONEY'), ('BRK_CM', 'BROKER_COMMISSION'), ('ERR', 'ERROR')], max_length=10)),
                ('datetime', models.DateTimeField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.bill')),
                ('brocker_periodic_commissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='History.brockerperiodiccommissions')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.currency')),
                ('share_by_divident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.share')),
            ],
        ),
        migrations.CreateModel(
            name='InvestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('money_deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='History.moneydeal')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.share')),
                ('share_deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='History.sharedeal')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchangeDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('currency_from_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_to_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='History.bill')),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='History.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='History.currency')),
            ],
        ),
    ]
