# Generated by Django 4.0.3 on 2022-10-25 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('History', '0005_alter_importbrockerdatalog_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalshare',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='historicalshare',
            name='currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='History.currency'),
        ),
        migrations.AddField(
            model_name='share',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='History.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='brocker_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='bill_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='brocker_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='importbrockerdatalog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 12, 29, 56, 580446)),
        ),
    ]
