# Generated by Django 4.0.3 on 2022-11-01 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('History', '0006_rename_company_name_historicalshare_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchangedeal',
            name='import_brocker_data_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='History.importbrockerdatalog'),
        ),
        migrations.AddField(
            model_name='historicalcurrencyexchangedeal',
            name='import_brocker_data_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='History.importbrockerdatalog'),
        ),
        migrations.AddField(
            model_name='historicalmoneydeal',
            name='import_brocker_data_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='History.importbrockerdatalog'),
        ),
        migrations.AddField(
            model_name='historicalsharedeal',
            name='import_brocker_data_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='History.importbrockerdatalog'),
        ),
        migrations.AddField(
            model_name='moneydeal',
            name='import_brocker_data_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='History.importbrockerdatalog'),
        ),
        migrations.AddField(
            model_name='sharedeal',
            name='import_brocker_data_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='History.importbrockerdatalog'),
        ),
        migrations.AlterField(
            model_name='importbrockerdatalog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 23, 43, 13, 734570)),
        ),
        migrations.AlterField(
            model_name='importbrockerdatalog',
            name='status_code',
            field=models.IntegerField(
                choices=[(0, 'Не начато'), (1, 'Начато'), (2, 'Завершено успешно'), (-1, 'Завершено с ошибкой')],
                default=0),
        ),
    ]
