# Generated by Django 4.0.3 on 2022-11-01 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('History', '0007_currencyexchangedeal_import_brocker_data_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbrockerdatalog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 23, 44, 9, 265552)),
        ),
    ]
