# Generated by Django 4.1 on 2022-11-15 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('History', '0011_historicalmoneydeal_comment_moneydeal_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoneydeal',
            name='type_of_deal',
            field=models.CharField(choices=[('BUYING_SHARES', 'Покупка акций'), ('SALE_OF_SHARES', 'Продажа акций'),
                                            ('DIVIDENT_PAYMENT', 'Выплата дивидендов/купонов'),
                                            ('BUYING_BOND', 'Покупка облигаций'), ('SALE_OF_BOND', 'Продажа облигаций'),
                                            ('REFILL_MONEY', 'Внесение денег на счет'),
                                            ('WITHDRAWAL_MONEY', 'Вывод денег со счета'),
                                            ('BROKER_COMMISSION', 'Брокерская комиссия'), ('TAX', 'Налоги'),
                                            ('UNKNOWN', 'Не распознанный тип'), ('ERROR', 'Ошибка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsharedeal',
            name='type_of_deal',
            field=models.CharField(choices=[('BUYING_SHARES', 'Покупка акций'), ('SALE_OF_SHARES', 'Продажа акций'),
                                            ('DIVIDENT_PAYMENT', 'Выплата дивидендов/купонов'),
                                            ('BUYING_BOND', 'Покупка облигаций'), ('SALE_OF_BOND', 'Продажа облигаций'),
                                            ('REFILL_MONEY', 'Внесение денег на счет'),
                                            ('WITHDRAWAL_MONEY', 'Вывод денег со счета'),
                                            ('BROKER_COMMISSION', 'Брокерская комиссия'), ('TAX', 'Налоги'),
                                            ('UNKNOWN', 'Не распознанный тип'), ('ERROR', 'Ошибка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importbrockerdatalog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 23, 11, 33, 206264)),
        ),
        migrations.AlterField(
            model_name='moneydeal',
            name='type_of_deal',
            field=models.CharField(choices=[('BUYING_SHARES', 'Покупка акций'), ('SALE_OF_SHARES', 'Продажа акций'),
                                            ('DIVIDENT_PAYMENT', 'Выплата дивидендов/купонов'),
                                            ('BUYING_BOND', 'Покупка облигаций'), ('SALE_OF_BOND', 'Продажа облигаций'),
                                            ('REFILL_MONEY', 'Внесение денег на счет'),
                                            ('WITHDRAWAL_MONEY', 'Вывод денег со счета'),
                                            ('BROKER_COMMISSION', 'Брокерская комиссия'), ('TAX', 'Налоги'),
                                            ('UNKNOWN', 'Не распознанный тип'), ('ERROR', 'Ошибка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedeal',
            name='type_of_deal',
            field=models.CharField(choices=[('BUYING_SHARES', 'Покупка акций'), ('SALE_OF_SHARES', 'Продажа акций'),
                                            ('DIVIDENT_PAYMENT', 'Выплата дивидендов/купонов'),
                                            ('BUYING_BOND', 'Покупка облигаций'), ('SALE_OF_BOND', 'Продажа облигаций'),
                                            ('REFILL_MONEY', 'Внесение денег на счет'),
                                            ('WITHDRAWAL_MONEY', 'Вывод денег со счета'),
                                            ('BROKER_COMMISSION', 'Брокерская комиссия'), ('TAX', 'Налоги'),
                                            ('UNKNOWN', 'Не распознанный тип'), ('ERROR', 'Ошибка')], max_length=20),
        ),
    ]
