# Generated by Django 4.1 on 2022-11-23 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('History', '0012_alter_historicalmoneydeal_type_of_deal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshare',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='share',
            name='currency',
        ),
        migrations.AlterField(
            model_name='importbrockerdatalog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 14, 21, 38, 844524)),
        ),
    ]
