# Generated by Django 4.1 on 2022-11-27 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("History", "0013_remove_historicalshare_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 14, 10, 42, 87696)
            ),
        ),
        migrations.CreateModel(
            name="AlternativeNameOfShare",
            fields=[
                (
                    "alt_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="History.share"
                    ),
                ),
            ],
        ),
    ]
