# Generated by Django 4.1 on 2022-11-27 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("History", "0014_alter_importbrockerdatalog_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alternativenameofshare",
            old_name="bill",
            new_name="share",
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 27, 14, 22, 38, 441463)
            ),
        ),
    ]
