# Generated by Django 4.1 on 2022-12-02 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "History",
            "0017_historicalsharedeal_board_name_sharedeal_board_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalshare",
            name="exchange_name",
        ),
        migrations.RemoveField(
            model_name="share",
            name="exchange_name",
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 2, 22, 17, 8, 106829)
            ),
        ),
    ]
