# Generated by Django 4.1 on 2022-12-04 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "History",
            "0018_remove_historicalshare_exchange_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbrockerperiodiccommissions",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="historicalbrockerperiodiccommissions",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmoneydeal",
            name="brocker_periodic_commissions",
        ),
        migrations.RemoveField(
            model_name="moneydeal",
            name="brocker_periodic_commissions",
        ),
        migrations.AddField(
            model_name="historicalmoneydeal",
            name="commission_currency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="History.currency",
            ),
        ),
        migrations.AddField(
            model_name="historicalmoneydeal",
            name="tax_currency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="History.currency",
            ),
        ),
        migrations.AddField(
            model_name="moneydeal",
            name="commission_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="History.currency",
            ),
        ),
        migrations.AddField(
            model_name="moneydeal",
            name="tax_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="History.currency",
            ),
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 4, 23, 0, 41, 651312)
            ),
        ),
        migrations.DeleteModel(
            name="BrockerPeriodicCommissions",
        ),
        migrations.DeleteModel(
            name="HistoricalBrockerPeriodicCommissions",
        ),
    ]
