# Generated by Django 4.1 on 2022-12-18 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("History", "0022_alter_importbrockerdatalog_datetime_repodeal_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AlternativeNameOfShare",
            new_name="ShareAlternativeName",
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 18, 21, 39, 41, 742533)
            ),
        ),
        migrations.CreateModel(
            name="CurrencyAlternativeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_code", models.CharField(max_length=7)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="History.currency",
                    ),
                ),
            ],
        ),
    ]
