# Generated by Django 4.1 on 2022-12-18 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("History", "0023_rename_alternativenameofshare_sharealternativename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencyalternativename",
            name="id",
        ),
        migrations.AlterField(
            model_name="currencyalternativename",
            name="alt_code",
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 18, 22, 13, 10, 577038)
            ),
        ),
    ]
