# Generated by Django 4.1 on 2022-12-19 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("History", "0024_remove_currencyalternativename_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalrepodeal",
            old_name="price_first_part",
            new_name="price_first_part_with_sign",
        ),
        migrations.RenameField(
            model_name="historicalrepodeal",
            old_name="price_second_part",
            new_name="price_second_part_with_sign",
        ),
        migrations.RenameField(
            model_name="repodeal",
            old_name="price_first_part",
            new_name="price_first_part_with_sign",
        ),
        migrations.RenameField(
            model_name="repodeal",
            old_name="price_second_part",
            new_name="price_second_part_with_sign",
        ),
        migrations.AddField(
            model_name="historicalrepodeal",
            name="direction_first_part",
            field=models.CharField(
                choices=[("SELL", "Продажа"), ("BUY", "Покупка")],
                default="SELL",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repodeal",
            name="direction_first_part",
            field=models.CharField(
                choices=[("SELL", "Продажа"), ("BUY", "Покупка")],
                default="SELL",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 19, 23, 14, 20, 882577)
            ),
        ),
    ]
