# Generated by Django 4.1 on 2023-01-04 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "History",
            "0025_rename_price_first_part_historicalrepodeal_price_first_part_with_sign_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmoneydeal",
            old_name="share_by_divident",
            new_name="share_by_dividend",
        ),
        migrations.RenameField(
            model_name="moneydeal",
            old_name="share_by_divident",
            new_name="share_by_dividend",
        ),
        migrations.AlterField(
            model_name="historicalmoneydeal",
            name="type_of_deal",
            field=models.CharField(
                choices=[
                    ("BUYING_SHARES", "Покупка акций"),
                    ("SALE_OF_SHARES", "Продажа акций"),
                    ("DIVIDEND_PAYMENT", "Выплата дивидендов/купонов"),
                    ("BUYING_BOND", "Покупка облигаций"),
                    ("SALE_OF_BOND", "Продажа облигаций"),
                    ("REFILL_MONEY", "Внесение денег на счет"),
                    ("WITHDRAWAL_MONEY", "Вывод денег со счета"),
                    ("BROKER_COMMISSION", "Брокерская комиссия"),
                    ("TAX", "Налоги"),
                    ("UNKNOWN", "Не распознанный тип"),
                    ("ERROR", "Ошибка"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsharedeal",
            name="type_of_deal",
            field=models.CharField(
                choices=[
                    ("BUYING_SHARES", "Покупка акций"),
                    ("SALE_OF_SHARES", "Продажа акций"),
                    ("DIVIDEND_PAYMENT", "Выплата дивидендов/купонов"),
                    ("BUYING_BOND", "Покупка облигаций"),
                    ("SALE_OF_BOND", "Продажа облигаций"),
                    ("REFILL_MONEY", "Внесение денег на счет"),
                    ("WITHDRAWAL_MONEY", "Вывод денег со счета"),
                    ("BROKER_COMMISSION", "Брокерская комиссия"),
                    ("TAX", "Налоги"),
                    ("UNKNOWN", "Не распознанный тип"),
                    ("ERROR", "Ошибка"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importbrockerdatalog",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 4, 20, 58, 48, 318844)
            ),
        ),
        migrations.AlterField(
            model_name="moneydeal",
            name="type_of_deal",
            field=models.CharField(
                choices=[
                    ("BUYING_SHARES", "Покупка акций"),
                    ("SALE_OF_SHARES", "Продажа акций"),
                    ("DIVIDEND_PAYMENT", "Выплата дивидендов/купонов"),
                    ("BUYING_BOND", "Покупка облигаций"),
                    ("SALE_OF_BOND", "Продажа облигаций"),
                    ("REFILL_MONEY", "Внесение денег на счет"),
                    ("WITHDRAWAL_MONEY", "Вывод денег со счета"),
                    ("BROKER_COMMISSION", "Брокерская комиссия"),
                    ("TAX", "Налоги"),
                    ("UNKNOWN", "Не распознанный тип"),
                    ("ERROR", "Ошибка"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sharedeal",
            name="type_of_deal",
            field=models.CharField(
                choices=[
                    ("BUYING_SHARES", "Покупка акций"),
                    ("SALE_OF_SHARES", "Продажа акций"),
                    ("DIVIDEND_PAYMENT", "Выплата дивидендов/купонов"),
                    ("BUYING_BOND", "Покупка облигаций"),
                    ("SALE_OF_BOND", "Продажа облигаций"),
                    ("REFILL_MONEY", "Внесение денег на счет"),
                    ("WITHDRAWAL_MONEY", "Вывод денег со счета"),
                    ("BROKER_COMMISSION", "Брокерская комиссия"),
                    ("TAX", "Налоги"),
                    ("UNKNOWN", "Не распознанный тип"),
                    ("ERROR", "Ошибка"),
                ],
                max_length=20,
            ),
        ),
    ]
